apiVersion: v1
kind: ConfigMap
metadata:
  name: esustellar-config
  namespace: esustellar-testnet
  labels:
    app: esustellar-web
    environment: testnet
data:
  NEXT_PUBLIC_SAVINGS_CONTRACT_ID: ""
  NEXT_PUBLIC_REGISTRY_CONTRACT_ID: ""
  NEXT_PUBLIC_CONTRACT_ID: ""
