apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: esustellar-monitoring
resources:
  - prometheus-deployment.yaml
  - alertmanager-deployment.yaml
configMapGenerator:
  - name: prometheus-alert-rules
    files:
      - alert-rules.yaml
