apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: esustellar-web
  namespace: esustellar
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - esustellar.io
      secretName: esustellar-web-tls
  rules:
    - host: esustellar.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: esustellar-web
                port:
                  name: http
