apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: esustellar
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - certificate.yaml
commonLabels:
  app.kubernetes.io/part-of: esustellar
