apiVersion: v1
kind: Service
metadata:
  name: esustellar-web
  namespace: esustellar
  labels:
    app: esustellar-web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      name: http
  selector:
    app: esustellar-web
